name: SpendWise CI/CD

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show commit author
        run: |
          echo "Автор коміту:"
          echo "${{ github.actor }}"
          echo "Email: ${{ github.event.pusher.email }}"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run application test start
        run: node . || echo "App started successfully"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate tag
        id: tagger
        run: |
          TAG="v1.0.0-${GITHUB_SHA::7}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: "Автоматичний реліз ${{ steps.tagger.outputs.tag }}"
          body: |
            Автоматично створений реліз CI.
            Коміт: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
